# Site settings
title: mynote
email: bang.nguyen47@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My note
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bangnguyen47.github.io/" # the base hostname & protocol for your site
twitter_username: bangnguyen47
github_username:  bangnguyen47

# Build settings
markdown: kramdown
